version: 2

project_name: quickstart

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

universal_binaries:
  - replace: false

builds:
  - id: "dgrkt-cli-build"
    binary: "dgrkt"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X {{.ModulePath}}/app.Version={{.Version}}
      - -X {{.ModulePath}}/app.CommitHash={{.ShortCommit}}
      - -X {{.ModulePath}}/app.BuildDate={{.CommitDate}}
      - -X {{.ModulePath}}/app.Portable=false
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: "dgrkt-portable-build"
    binary: "dgrkt-portable"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X {{.ModulePath}}/app.Version={{.Version}}
      - -X {{.ModulePath}}/app.CommitHash={{.ShortCommit}}
      - -X {{.ModulePath}}/app.BuildDate={{.CommitDate}}
      - -X {{.ModulePath}}/app.Portable=true
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: "dgrkt-cli-archive"
    formats: ['tar.gz']
    ids:
      - dgrkt-cli-build
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
  - id: "dgrkt-portable-archive"
    formats: ['tar.gz']
    ids:
      - dgrkt-portable-build
    name_template: "{{ .ProjectName }}-portable_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: TPIsoftwareOSPO
    name: quickstart
  name_template: "Release {{ .Tag }}"


homebrew_casks:
  - name: dgrkt
    repository:
      owner: TPIsoftwareOSPO
      name: homebrew-tap
    homepage: "https://github.com/TPIsoftwareOSPO/quickstart"
    description: "Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
    ids:
      - dgrkt-cli-archive

scoops:
  - repository:
      owner: TPIsoftwareOSPO
      name: scoop-bucket
    name: dgrkt
    directory: bucket
    homepage: "https://github.com/TPIsoftwareOSPO/quickstart"
    description: "A command orchestration tool for declarative task execution."
    ids:
      - dgrkt-cli-archive

dockers:
  - id: "dgrkt-docker-amd64"
    ids:
      - dgrkt-cli-build
    use: buildx
    goarch: amd64
    image_templates:
      - "tpisoftwareopensource/dgrkt:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.description=Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    extra_files:
      - README.md
      - LICENSE
  - id: "dgrkt-docker-arm64"
    use: buildx
    goarch: arm64
    image_templates:
      - "tpisoftwareopensource/dgrkt:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.description=Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    extra_files:
      - README.md
      - LICENSE

docker_manifests:
  - name_template: "tpisoftwareopensource/dgrkt:{{ .Version }}"
    image_templates:
      - "tpisoftwareopensource/dgrkt:{{ .Version }}-amd64"
      - "tpisoftwareopensource/dgrkt:{{ .Version }}-arm64"
  - name_template: "tpisoftwareopensource/dgrkt:latest"
    image_templates:
      - "tpisoftwareopensource/dgrkt:{{ .Version }}-amd64"
      - "tpisoftwareopensource/dgrkt:{{ .Version }}-arm64"


snapshot:
  version_template: "{{ .Version }}-snapshot"

gomod:
  proxy: true

report_sizes: true
  
sboms:
  - id: dgrkt-sbom
    disable: false
    ids:
      - dgrkt-cli-archive
      - dgrkt-portable-archive
    documents:
      - "${artifact}.sbom.json"

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^chore: update$"
      - "^chore: docs$"
      - "^docs: update$"
      - "^chore: schema$"
      - "^chore: typo$"
      - "^chore: auto-update generated files$"
      - "^chore: update schema$"
      - "^chore: schema update$"
      - "^chore\\(deps\\): "
      - "^(build|ci): "
      - "merge conflict"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999